lod:
  - time: 0
    channels:
      - 7
  - time: 3
    channels:
      - 1
  - time: 6
    channels:
      - 1
  - time: 9
    channels:
      - 2
  - time: 12
    channels:
      - 3
  - time: 15
    channels:
      - 2
      - 3
      - 6
  - time: 18
    channels:
      - 4
      - 5
      - 7
  - time: 21
    channels:
      - 4
      - 5
      - 6

lol:
  - time: 0
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 2
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 4
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 6
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 8
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 10
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 12
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 14
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 16
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 18
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 20
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 22
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7