ic:
  - time: 0:00
    channels:
      - 1
      - 2
      - 3
  - time: 2:00
    channels:
      - 1
      - 2
      - 3
  - time: 4:00
    channels:
      - 1
      - 2
      - 3
  - time: 6:00
    channels:
      - 1
      - 2
      - 3
  - time: 8:00
    channels:
      - 1
      - 2
      - 3
  - time: 10:00
    channels:
      - 1
      - 2
      - 3
  - time: 12:00
    channels:
      - 1
      - 2
      - 3
  - time: 14:00
    channels:
      - 1
      - 2
      - 3
  - time: 16:00
    channels:
      - 1
      - 2
      - 3
  - time: 18:00
    channels:
      - 1
      - 2
      - 3
  - time: 20:00
    channels:
      - 1
      - 2
      - 3
  - time: 22:00
    channels:
      - 1
      - 2
      - 3

asgo:
  - time: 11:30
    channels:
      - 1
      - 2
      - 3
  - time: 17:30
    channels:
      - 1
      - 2
      - 3
  - time: 21:30
    channels:
      - 1
      - 2
      - 3
  - time: 23:30
    channels:
      - 1
      - 2
      - 3

lod:
  - time: 0:00
    channels:
      - 7
  - time: 3:00
    channels:
      - 1
  - time: 6:00
    channels:
      - 1
  - time: 9:00
    channels:
      - 2
  - time: 12:00
    channels:
      - 3
  - time: 15:00
    channels:
      - 2
      - 3
      - 6
  - time: 18:00
    channels:
      - 4
      - 5
      - 7
  - time: 21:00
    channels:
      - 4
      - 5
      - 6

lol:
  - time: 0:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 2:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 4:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 6:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 8:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 10:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 12:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 14:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 16:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 18:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 20:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - time: 22:00
    channels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7